Repository hcengineering/platform, pull requests merged in 2022-04, with the labels that each got.

#1276 Add ".nvmrc"
  .nvmrc
Labels: enhancement

#1284 Migrate thread messages
  models/chunter/src/index.ts
  models/chunter/src/migration.ts
  plugins/chunter-resources/src/components/Channel.svelte
  plugins/chunter-resources/src/components/ChannelView.svelte
  plugins/chunter-resources/src/components/ThreadComment.svelte
  plugins/chunter-resources/src/components/ThreadView.svelte
  plugins/chunter-resources/src/index.ts
  plugins/chunter/src/index.ts
Labels: updates model

#1586 minor table loading fix again
  plugins/view-resources/src/components/Table.svelte
Labels: bug
